# Generated by Django 2.2 on 2020-04-16 11:54

from django.db import migrations, models
import reportlab.graphics.shapes


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0002_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBarChartDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, reportlab.graphics.shapes.Drawing),
        ),
    ]
