# Generated by Django 2.2 on 2020-04-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0003_mybarchartdrawing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='Answer',
        ),
    ]
