# Generated by Django 2.2 on 2020-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0004_auto_20200416_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qestion',
            new_name='question',
        ),
    ]
