# Generated by Django 2.2 on 2020-04-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0005_auto_20200416_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
