# Generated by Django 2.2 on 2020-04-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0008_ans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
