# Generated by Django 2.2 on 2020-04-20 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0009_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalKoronaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('label', models.TextField()),
                ('last_pull_date', models.DateTimeField(default=datetime.datetime(2020, 1, 11, 19, 19, 28, 672008, tzinfo=utc), verbose_name='last pulled')),
            ],
        ),
    ]
