# Generated by Django 2.2 on 2020-04-20 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0010_externalkoronadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalkoronadata',
            old_name='label',
            new_name='bar_labels',
        ),
        migrations.RemoveField(
            model_name='externalkoronadata',
            name='last_pull_date',
        ),
        migrations.AddField(
            model_name='externalkoronadata',
            name='pull_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 20, 2, 43, 540721, tzinfo=utc)),
        ),
    ]
