# Generated by Django 2.2 on 2020-04-22 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0011_auto_20200420_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalkoronadata',
            name='pull_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 15, 29, 33, 442005, tzinfo=utc)),
        ),
    ]
