# Generated by Django 2.2 on 2020-04-25 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0014_auto_20200423_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBarChartDrawing',
        ),
        migrations.AddField(
            model_name='ans',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
