# Generated by Django 2.2 on 2020-04-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsiha_app', '0016_ans_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
